- name: Install brew
  include_role:
    name: geerlingguy.mac.homebrew
  tags:
    - brew
    - install
- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root
- name: "Install homebrew packages"
  community.general.homebrew:
    name: [
      'coreutils',
      'curl',
      'gpg',
      'gcc',
      'libtool',
      'libxslt',
      'libyaml',
      'unzip',
      'gh',
    ]
    state: present
    update_homebrew: yes
  tags:
    - brew
    - install
- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - visual-studio-code
    - hammerspoon
  tags:
    - install
    - brew
