- name: "Install homebrew packages"
  community.general.homebrew:
    name: [
      'coreutils',
      'curl',
      'fzf',
      'gpg',
      'libtool',
      'libxslt',
      'libyaml',
      'tmux',
      'unzip',
      'vim',
      'yarn',
    ]
    state: present
    update_homebrew: yes
  tags:
    - brew
    - install