 - name: Install core packages via brew casks
   community.general.homebrew_cask:
    name: "{{ item }}"
   ignore_errors: yes
   with_items:
    - docker
    - google-chrome
    - google-cloud-sdk
    - slack
    - visual-studio-code
    - zoom
    - brave
   tags:
      - install
      - brew