- name: Install brew
  include_role:
    name: geerlingguy.mac.homebrew
    apply:
      environment:
        PATH: '{{homebrew_install_path}}/bin:{{ ansible_env.PATH }}'
  tags:
    - brew
    - install
- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root
- name: Add brew to path
  shell: ln -s /opt/homebrew/Homebrew/bin/brew /usr/local/bin
  become: true
  become_user: root
- name: "Install homebrew packages"
  community.general.homebrew:
    name: [
      'coreutils',
      'curl',
      'fzf',
      'gpg',
      'libtool',
      'libxslt',
      'libyaml',
      'tmux',
      'unzip',
      'vim',
      'yarn',
    ]
    state: present
    update_homebrew: yes
    path: '/usr/local/bin:/opt/homebrew/bin'
    become: true
    become_user: root
  tags:
    - brew
    - install
- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - docker
    - slack
    - visual-studio-code
    - brave-browser
  tags:
    - install
    - brew