- name: Installing stow
  community.general.homebrew:
      name: stow
  tags:
    - install
    - dotfiles
    - stow
    - nvim
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/daespuor/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
    - nvim
- name: Add permissions to macOx
  shell: find {{ lookup('env', 'HOME') }}/dotfiles -type f -exec chmod +x {} \;
  become: true
  become_user: root
  tags:
    - install
    - dotfiles
    - stow
    - nvim
- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./macOx
  tags:
    - install
    - dotfiles
    - stow
    - nvim
