- name: Installing stow
  community.general.homebrew:
      name: ['stow']
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/daespuor/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Add permissions to macOx
  shell: chmod +x $HOME/dotfiles/macOx
  become: true
- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./macOx
  tags:
    - install
    - dotfiles
    - stow