- name: Install node and npm
  community.general.homebrew: 
    name: ['nodejs', 'npm']
  tags:
    - node
    - install
- name: Install n
  npm:
    name: n
    global: true
  tags:
    - node
    - install
- name: Install node 14
  shell: n 14
  tags:
    - node
    - install