- name: Install nvm 
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  tags:
    - node
    - install
- name: Install node
  ansible.builtin.shell: >
    nvm install latest
  tags:
    - node
    - install
- name: Install corepack
  community.general.homebrew:
    name: ['corepack']
  tags:
    - node
    - install
- name: Enable corepack
  ansible.builtin.shell: >
    corepack enable
  tags:
    - node
    - install
