- name: Install yabai
  community.general.homebrew:
      name: ['koekeishiya/formulae/yabai']
  tags:
    - install
    - yabai
- name: Install jq a flexible command line JSON processor
  community.general.homebrew:
      name: ['jq']
  tags:
    - install
    - yabai
- name: Install skhd simple hot key deamon for MacOs
  community.general.homebrew:
      name: ['koekeishiya/formulae/skhd']
  tags:
    - install
    - yabai
- name: Download limelight
  ansible.builtin.git:
    repo: 'https://github.com/koekeishiya/limelight.git'
    dest: "{{ lookup('env', 'HOME') }}/limelight"
  tags:
    - install
    - yabai
- name: Install limelight
  shell: make {{ lookup('env', 'HOME') }}/limelight && ln -s {{ lookup('env', 'HOME') }}/limelight/bin /usr/local/bin/limelight
  become: true
  become_user: root
  tags:
    - install
    - yabai
- name: Add permissions to yabai & skhd
  shell: find {{ lookup('env', 'HOME') }}/scripts -type f -exec chmod +x {} \;
  become: true
  become_user: root
  tags:
    - install
    - yabai