- name: Install yabai
  ansible.builtin.shell: >
    brew install koekeishiya/formulae/yabai
  tags:
    - install
    - yabai
- name: Install jq a flexible command line JSON processor
  community.general.homebrew:
      name: ['jq']
  tags:
    - install
    - yabai
- name: Install skhd simple hot key deamon for MacOs
  community.general.homebrew:
      name: ['koekeishiya/formulae/skhd']
  tags:
    - install
    - yabai
- name: Add permissions to yabai & skhd
  shell: find {{ lookup('env', 'HOME') }}/.config/skhd/scripts -type f -exec chmod +x {} \;
  become: true
  become_user: root
  tags:
    - install
    - yabai
