- name: Install zsh
  community.general.homebrew:
    name: ['zsh']
  tags:
    - zsh
    - install
- name: Which zsh
  shell: chsh -s `which zsh` # when typing this I did chsh zsh
  tags:
    - zsh
    - install
- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - zsh
    - install